sudo: required
services:
  - docker

before_install:
  - docker build -t andythenuge/docker-react -f Dockerfile.dev .

script:
  - docker run andythenuge/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-461373311785"
  bucket_path: "DockerReact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"